import { Poppins } from "next/font/google";
import "./globals.css";
import Navber from "@/component/Navber";
import Footer from "@/component/Footer";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${popins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navber></Navber>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
