import { Poppins } from "next/font/google";
import "./globals.css";
import AppLoader from "@/component/AppLoader";
import { Toaster } from "react-hot-toast";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${popins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppLoader>
   
          <Toaster />
        {children}
        
        </AppLoader>
        </body>
    </html>
  );
}
